### ISSUE TITLE
[Feature] Manual Blacklist By World ID

### ISSUE THREAD

**Issue by MintLily** [AdGoBye/AdGoBye#103]
### Add manual world blacklist from modifying asset bundles.
Add `List<string>` of world IDs to entirely skip bundle modification.

something something `if (config.skipList.Contains(currentworld.Id) { /* some method to skip */ }`

**Comment by regalialong** [comment]
For what it's worth, that's how it used to be, the refactors probably changed that behavior.

I'll look into fixing that at some point.

**Comment by regalialong** [comment]
Oh, this was a bit game-of-telephone-y but I think you're looking for `appsettings.json`'s `Allowlist`. It takes IDs that are skipped by the Indexer, which means AGB ignores the existence of that piece of content.
