### ISSUE TITLE
Deadlock of Hell

### ISSUE THREAD

**Issue by regalialong** [AdGoBye/AdGoBye#11]
a7684660b5fe801e3d096e1555cfe075f5c57620
ce7bed40a57a43f90417c8eec78483a1c05e9576

There have been repeated instances where a shared static `Serilog.ILogger` instance caused the code to halt if it was parallelized per `Parallel.ForEach`. After either removing the comment, logging per the static global `Log.Logger`, or giving every thread its own logger instance like ce7bed40a57a43f90417c8eec78483a1c05e9576 did, the code works again.

![Debugger gets stuck on Logger.Warning](https://github.com/AdGoBye/AdGoBye/assets/126194895/e3f81e0c-b9c7-436b-9d4b-e11475db6855)

This is nearing showstopper since it either requires:
- not contextually logging whenever a method is parallelized (which we may not have control [due to Plugins] if we decide to parallelize patching and can quickly become viral)
- not contextually logging (which makes the logs less useful since it helps knowing what component is logging)
- not parallelizing (which would likely have a performance impact)

All three of these are varying amounts of undesirable.

**Comment by DubyaDude** [comment]
@regalialong Is this still something you want to keep open? I believe this would no longer be an issue in V2.

**Comment by regalialong** [comment]
Sort of, we don't use parallel in v2 right now but adding to the Index would be parallelizable if the DoH didn't exist, it blocks doing that.
