### ISSUE TITLE
Adlily is dead (sent a cease & desist)

### ISSUE THREAD

**Issue by thegu5** [AdGoBye/AdGoBye#18]
:crab: :crab: :crab:

Maybe update the readme with a different example or make it past tense?

https://twitter.com/ariesrclark/status/1735073306531832049
![image](https://github.com/AdGoBye/AdGoBye/assets/58223632/96e14b62-6a39-4bf9-a744-2ac83fb14cad)
![image](https://github.com/AdGoBye/AdGoBye/assets/58223632/856de088-894b-46f7-bf7d-6a4e59bd91dc)
![image](https://github.com/AdGoBye/AdGoBye/assets/58223632/9cbbca26-72ac-4357-a13d-68f3db9f08e6)

**Comment by Myrkie** [comment]
fantastic outcome.

**Comment by regalialong** [comment]
It probably wouldn't hurt to freshen up the README in general, it was hastily written. [They still seem to be hinting towards a return in some form](https://nitter.dafriser.be/AdlilyVR/status/1735073703971410133).

I think the spirit of the text is still valid though, we should be opposing actors *like* Adlily. They serve as an example of the corporatization that will end up hurting the SocVR community.

If you want an example of that, Aries is [postmortem advertising](https://nitter.dafriser.be/ariesrclark/status/1735080914919510066) a opt-out mechanism that resolves to 404.
![](https://github.com/AdGoBye/AdGoBye/assets/126194895/a6482ec9-9beb-4442-9788-b4469f929157)
![](https://github.com/AdGoBye/AdGoBye/assets/126194895/103702df-2fad-403c-a63d-4bfb21e76ef1)

**Comment by regalialong** [comment]
a82083564715f420cb406104b6bc843bfcb99576

**Comment by regalialong** [comment]
> It probably wouldn't hurt to freshen up the README in general, it was hastily written. [They still seem to be hinting towards a return in some form](https://web.archive.org/web/20231214024651/https://nitter.dafriser.be/AdlilyVR/status/1735073703971410133).

[Turns out they did in fact continue development despite being asked to stop](https://web.archive.org/web/20250329021616/https://github.com/adlily-hq/adlily-vpm/commits/main). Very curious, someone playing a gambit here or are they suddenly fine with ad networks? :shipit:

**Comment by thegu5** [comment]
Hmmmmmmm (how naive I was...)
The docs are updated with new features/ui too.
