### ISSUE TITLE
How do I add block lists? Are there any existing block lists?

### ISSUE THREAD

**Issue by ShayBox** [AdGoBye/AdGoBye#24]
When I launch the program, I see `No blocklist has been loaded, is this intentional?`

**Comment by Myrkie** [comment]
premade block-lists can be downloaded from [AGB Blocklists](https://github.com/AdGoBye/AdGoBye-Blocklists)

**Comment by ShayBox** [comment]
Ah thank you

**Comment by Bluscream** [comment]
> premade block-lists can be downloaded from [AGB Blocklists](https://github.com/AdGoBye/AdGoBye-Blocklists)

You should really add a "Installation & Usage" section to the readme ^^
