### ISSUE TITLE
Plugin Reapply

### ISSUE THREAD

**Issue by regalialong** [AdGoBye/AdGoBye#30]
This is a rephrase from a user story, I've received messages about users who were expecting new versions of Plugins to reapply. We didn't check if Plugins applied and as a side-effect always ran them, which was never intentional.

Since we now externally track if a Plugin applied, we don't do this anymore.

I think there are two methods that can solve this:
- Unmanaged: Always call `Verify` for Plugins to allow them to check themselves if they should apply
- Managed: Hash the Plugin file, store this into the database and then check if this has changed, then reapply based on the result of that

**Comment by DubyaDude** [comment]
I'd prefer a Managed solution, though checking against hash I'm not too sure about.
Might be better for the plugin to self-identify a version number.

**Comment by regalialong** [comment]
I think using version number could be annoying for developers since they'd be require to bump version number every time something changes, which is sane [this is how it should be for released software!] but sounds annoying for iterating quickly.

We can assume if a Plugin changes, they probably want to patch again. It's the job of Verify to check if a Plugin is valid to be applied either way.

**Comment by DubyaDude** [comment]
Maybe let the plugin decide whether it wants to be updated based on hash?
From a developer's standpoint, I hated re-applying things based on hash every time I recompile something to test something unrelated.

**Comment by regalialong** [comment]
I don't like introducing more logic for plugins since this requires additions to the Plugin interface, I don't want to add more things to it without asking for comments first.
Plugin logic already has a lot of moving parts and that's before #8 is a thing.

But sure, we can go with a versioned Managed approach. If there's sane tooling that can automatically attach commit hash as build info or just autoincrement versioning, we'd in theory have the best of both worlds.

Do you think it would make sense to pull in a library to properly parse the version string or should we just match if the string is the same in the Index?
