### ISSUE TITLE
Enforce Single Instance

### ISSUE THREAD

**Issue by DubyaDude** [AdGoBye/AdGoBye#37]
Currently, the program can be launched multiple times by the user, causing funky behavior.
We should check for and enforce a single instance-only run.

Possible implementation includes a global mutex: https://stackoverflow.com/a/522874/12657868

**Comment by regalialong** [comment]
How does the Mutex behave when the app fatally crashes?

**Comment by regalialong** [comment]
@DubyaDude I'm casually testing this on Linux with this added under the Logger:
```cs
var mutex = new Mutex (false, "AGB");
if (!mutex.WaitOne())
{
    Log.Fatal("Only a single instance of AGB should be running.");
    return;
}
```
This appears to have no effect when I run two instances of AGB, am I using it wrong?

**Comment by DubyaDude** [comment]
Ran across [this blog](https://www.medo64.com/2022/12/single-instance-application-for-net-6-or-7/) where he provided [this class](https://github.com/medo64/Medo/blob/main/src/Medo/Application/SingleInstance.cs) where it's used in [this code](https://github.com/medo64/Medo/blob/main/examples/SingleInstanceApplication/App.cs).

Confirmed it works both in Linux and Windows.

https://github.com/AdGoBye/AdGoBye/assets/13679909/c958c09f-e464-488d-9a3a-3806d9721444

https://github.com/AdGoBye/AdGoBye/assets/13679909/2445dd02-2d95-4574-bb00-4ce323bce6a9

**Comment by regalialong** [comment]
Code looks fine to me, it's MIT licensed so we could reasonably take it whole.
If you want to do that, you have my blessing, else I'll do it when I find the time.
