### ISSUE TITLE
Improve game appmanifest detection to handle non-default library paths

### ISSUE THREAD

**Issue by TayouVR** [AdGoBye/AdGoBye#49]
```
[08:34:46 FTL Indexer] We're unable to find your game's working folder (the folder above the cache), please provide it manually in appsettings.json as 'WorkingFolder'.
Unhandled exception. System.TypeInitializationException: The type initializer for 'AdGoBye.Indexer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not find file 'W:\scoop\apps\steam\current\steamapps\appmanifest_438100.acf'.
File name: 'W:\scoop\apps\steam\current\steamapps\appmanifest_438100.acf'
   at AdGoBye.Indexer.<GetApplicationName>g__DieFatally|13_1(Exception e)
   at AdGoBye.Indexer.GetApplicationName()
   at AdGoBye.Indexer.GetWorkingDirectory()
   at AdGoBye.Indexer..cctor()
   --- End of inner exception stack trace ---
   at AdGoBye.Indexer.GetCacheDir()
   at AdGoBye.Indexer.ManageIndex()
   at Program.<Main>$(String[] args)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```
the manifest in question is in `W:\SteamLibrary\steamapps\appmanifest_438100.acf`

**Comment by Myrkie** [comment]
you provide the game appdata folder path not app manifest aka roaming

**Comment by TayouVR** [comment]
> you provide the game appdata folder path not app manifest aka roaming, this is the folder before `Cache-WindowsPlayer`

this is on a fresh install with nothing provided. I assume AGB is trying to read some information from the app manifest
ofc when I provide the path it works as intended. But the stacktrace above suggests agb is trying to read the manifest for one reason or another and failing as it looked in the wrong steam library folder.

**Comment by Myrkie** [comment]
> > you provide the game appdata folder path not app manifest aka roaming, this is the folder before `Cache-WindowsPlayer`
> 
> this is on a fresh install with nothing provided. I assume AGB is trying to read some information from the app manifest ofc when I provide the path it works as intended. But the stacktrace above suggests agb is trying to read the manifest for one reason or another and failing as it looked in the wrong steam library folder.

no its not, agb needs the path to your cache is in which also contains output logs, its trying automatically to read your manifest to find it and its failing so give it your "working directory"

**Comment by TayouVR** [comment]
https://github.com/AdGoBye/AdGoBye/blob/f758775c4b4902f43c47a22c16639c6ff7954a45/AdGoBye/Indexer.cs#L525

**Comment by Myrkie** [comment]
this was a misunderstanding and this is actually a bug report, maybe users should be given permission to tag there own posts @regalialong

**Comment by regalialong** [comment]
Yep, this is somewhat expected, we're making the assumption that where your Steam installation folder is will also contain your library folder. That's not inherently correct and this detection is best-effort, I'd have to dig through the vdf files again to see where Steam stores that.

While I could work on a better mechanism, this is only used to pull metadata to build the actual game path.
https://github.com/AdGoBye/AdGoBye/blob/f758775c4b4902f43c47a22c16639c6ff7954a45/AdGoBye/Indexer.cs#L478-L479

You're better off bypassing this by providing the folder above your game cache folder (the one with the logs) by using `WorkingFolder` if you aren't going to move your cache folder too often.

I suppose maybe I should rephrase the error a little.

**Comment by TayouVR** [comment]
just made this issue to track the steam library path, and from there game cache path detection

**Comment by regalialong** [comment]
`$(SteamRoot)/config/libraryfolders.vdf` contains the library locations with a `apps` key that corresponds to the App IDs of the applications in those libraries, so if we want to keep the appmanifest method, that'd be the way go forward:

- Detect Steam Root over registry (on Linux assume `~/.steam/steam` will exist since I doubt Valve will be adopting [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) anytime soon)
- Check if default Steam library directory exists
  - If not, naively parse over `libraryfolders.vdf` to find library that holds the game:
    - Find line that contains `"path"`, extract path and store it temporarily
    - Loop until we hit a line that contains `"apps"`
    - Check every line for the ID we need
    - If we hit `}` before finding the ID, loop until we find it or fail
- Go to library folder and read appmanifest
- Panic if any step fails

Alternatively we could swap this out for `$(SteamRoot)/config/steamapps.vrmanifest` which also contains the name and isn't dependent on library location. Although I'm not sure when this file is created, probably prerequisites SteamVR.
I'll have to spin up a VM and test.

**Comment by regalialong** [comment]
https://github.com/WilliamVenner/steamlocate-rs which realistically is what we want to look off, they actually employ a vdf parser but in essence do the same thing with actual objects

https://github.com/WilliamVenner/steamlocate-rs/blob/master/src/library.rs#L45
https://github.com/WilliamVenner/steamlocate-rs/blob/master/src/library.rs#L143
