### ISSUE TITLE
File deletions aren't handled

### ISSUE THREAD

**Issue by TheMrGong** [AdGoBye/AdGoBye#6]
If you clear your cache and run AdGoBye, it'll still attempt to run all plugins with old cache'd files.

**Comment by regalialong** [comment]
https://github.com/AdGoBye/AdGoBye/blob/378c22c9baeb505200d8d2d27a78fff885d6aa4d/AdGoBye/Indexer.cs#L44-L45

This is handled by the Indexer per the directory hash on run. Try on a non-cleared cache, let it generate an Index, then rename `cache.json` to whatever and change your cache files.

Is the `Hash` in cache.json the same between those files?
