### ISSUE TITLE
Need event after writing

### ISSUE THREAD

**Issue by DubyaDude** [AdGoBye/AdGoBye#71]
Please create a new plugin method that triggers after the file is written.

**Comment by regalialong** [comment]
The situation is kinda a PITA because we'd have to loop over the Plugins again even though Plugins have already executed. It's not impossible, just annoying.

Are you sure this should absolutely be handled by Plugins? I was intending on adding patch finish notifications eventually, the reason why it isn't here is that most focus has been on core systems.

**Comment by DubyaDude** [comment]
This was what I intended `PostPatch` to be initially, but didn't catch that.

**Comment by DubyaDude** [comment]
Just to note, a fork of this already exists that we've ended up moving to because we deemed this rather important: https://github.com/TheMrGong/AdGoBye

**Comment by regalialong** [comment]
Right, essentially what I'm asking is if this shouldn't be moved into AGB's responsibility as a notification system or if it's really important that Plugins handle it per custom code. I'm fine with merging https://github.com/TheMrGong/AdGoBye/commit/61893fa3877779ddfb19a17083a8ec45421ee4ea if it's really important.

**Comment by DubyaDude** [comment]
There are different notification avenues, not going to name them here to reduce the chance of the project getting indexed.
Unless you want to go through the headache of supporting everything. Along with that, in our notifications we do display some data that pertains to the plugin itself, so you'd also need to somehow handle that.

I think it's best to let plugins handle it.

**Comment by DubyaDude** [comment]
If you truly want it to be a component of AGB natively, make that a 'official plugin'

**Comment by regalialong** [comment]
(sigh).

We don't control Plugin ordering and I think doing that would be a mess, I think it's best that we just merge the method with a minor version bump.

@TheMrGong You mind submitting a PR for https://github.com/TheMrGong/AdGoBye/commit/61893fa3877779ddfb19a17083a8ec45421ee4ea and bump the version of the Plugins again? I'll hand wave it to main.
