### ISSUE TITLE
Create a community space for AdGoBye

### ISSUE THREAD

**Issue by regalialong** [AdGoBye/AdGoBye#73]
Plugins v2 was up for a month in PR state to be reviewed but I realize that most people don't really follow development too hard, the result of that lack of communication / notification channel is #71. That's particularly a problem for Plugins who are dependents on what we do upstream.

While we have Discussions for discussing about AGB, where I've submitted some ideas before they became code, I think people don't follow that too much.

The people developing for AGB have been playing telephone with me over IM, we should have an IM channel instead. I've abstained from this before because I didn't want to moderate a space like this but the results speak for themselves.

I'm not sure yet where but it'll probably have to be Discord by network effect, Matrix is an obvious contender against that but I don't know how many people would be on board with that.

**Comment by regalialong** [comment]
Okay, I made a Matrix space at https://matrix.to/#/#adgobyeworks:catgirl.cloud for exploring how this will turn out

**Comment by DubyaDude** [comment]
I think the main issue we had in this release is that for a major change, there was no proper pre-release for plugin developers to take their time and migrate over, find potential issues, and design flaws.

To be blunt, the trigger to release was pulled far too quickly.

**Comment by DubyaDude** [comment]
I'd like to advocate changing `3.0.0` and 3.0.1 to be changed to pre-release and do a proper re-release of `3.1.0` with the massive amount of changes done.

**Comment by regalialong** [comment]
Alternatively if you're not fond of Matrix (I don't blame you), I've went ahead and bridged it to https://discord.gg/VgMnEr3xDk

**Comment by DubyaDude** [comment]
👍 

Guessing these just need to be added to README to consider it closed?
