### ISSUE TITLE
Version 4.0.0 Does not Launch on windows

### ISSUE THREAD

**Issue by RaspberryKitty1** [AdGoBye/AdGoBye#85]
I downloaded the latest built and tried to run it after adding the blocklist and it just does not run...
![image](https://github.com/AdGoBye/AdGoBye/assets/28585042/250b9812-70ea-49ab-a58c-ea2b52130ea8)

the previous build worked just fine no issues....
i tried with the game opened and closed.

**Comment by RaspberryKitty1** [comment]
reverting to 3.0.1 for now...

**Comment by regalialong** [comment]
Do you mind seeing if it launched with the `win-x64-build` artifact from https://github.com/AdGoBye/AdGoBye/actions/runs/9720349621? CI/CD didn't build the artifacts for this release for some reason so that might have been because of my build environment.

**Comment by RaspberryKitty1** [comment]
>Do you mind seeing if it works with the win-x64-build artifact from https://github.com/AdGoBye/AdGoBye/actions/runs/9720349621? CI/CD didn't build the artifacts for this release for some reason so that might have been because of my build environment.

yep that build worked

**Comment by regalialong** [comment]
I was able to repro this through Wine, my bad, I've built it again with the command from the CI/CD and replaced the files in the release.
