### ISSUE TITLE
Ship dotnet runtime with app.

### ISSUE THREAD

**Issue by DubyaDude** [AdGoBye/AdGoBye#89]
As discovered in https://github.com/AdGoBye/AdGoBye/discussions/87, people might run into hard crashes if they don't have the proper dotnet installed. I _believe_ there is a way to ship the application with an installer in case the user doesn't already have it.

Will need more research to see if doable.

**Comment by Myrkie** [comment]
you can do this by running .net publish as self contained this will make it independent of .net framework on the machine and instead ship the entire .net framework into it, I recommend using TRIM features if possible as shipping the entire .net runtime will balloon the binary size over 40MB, if proper source generators are implemented it would be best to use AOT publishing instead https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained

**Comment by DubyaDude** [comment]
I'd rather not deal with the headaches of trim or aot for debugging reasons.
I personally don't care for a larger binary and am okay with just doing a normal self-contained.

**Comment by regalialong** [comment]
About AOT, it's completely off the cards for us.
Microsoft [says for Native AOT that we cannot dynamically load code](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2Cwindows#limitations-of-native-aot-deployment), this would mean that AOT builds need to strip out / disable the Plugin system or that Plugins be built with AGB instead (à la Vencord). 

I think that would be a bad idea for unbenchmarked promises of "faster startup time and smaller memory footprints".
