### ISSUE TITLE
GetBaseField can fail to deseralize MonoBehaviour

### ISSUE THREAD

**Issue by regalialong** [AdGoBye/AdGoBye#93]
In Indexer, we have two places where we iterate over MonoBehaviours in an Asset and deserialize them:

https://github.com/AdGoBye/AdGoBye/blob/61608efa14a6110d782ce0f45a57853f7676bbcd/AdGoBye/Indexer.cs#L390-L393

https://github.com/AdGoBye/AdGoBye/blob/61608efa14a6110d782ce0f45a57853f7676bbcd/AdGoBye/Indexer.cs#L261-L266

~~Ignoring the incorrect variable names~~ The autopsy in #90 shows that `GetBaseField` can cause a Exception to bubble up here, we should catch it and `continue` on unparsable MonoBehaviours.

**Comment by Nirajan1-droid** [comment]
attempt
